l_simp_chinese:
 SETTING_INPUT_CONTEXT_COMMON:0 "普通"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP:1 "#todo 通用输入上下文的键绑定#!"

 SETTING_INPUT_ACTION_PAUSE:0 "暂停/解除暂停"
 SETTING_INPUT_ACTION_INCREASE_SPEED:0 "提高速度"
 SETTING_INPUT_ACTION_DECREASE_SPEED:0 "降低速度"
 SETTING_INPUT_ACTION_SPEED_ONE:0 "速度1"
 SETTING_INPUT_ACTION_SPEED_TWO:0 "速度2"
 SETTING_INPUT_ACTION_SPEED_THREE:0 "速度3"
 SETTING_INPUT_ACTION_SPEED_FOUR:0 "速度4"
 SETTING_INPUT_ACTION_SPEED_FIVE:0 "速度5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC:0 "播放/暂停音乐"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK:0 "下一首音乐"
 SETTING_INPUT_ACTION_CAMERA_UP:0 "镜头向上移动"
 SETTING_INPUT_ACTION_CAMERA_LEFT:0 "镜头向左移动"
 SETTING_INPUT_ACTION_CAMERA_DOWN:0 "镜头向下移动"
 SETTING_INPUT_ACTION_CAMERA_RIGHT:0 "镜头向右移动"
 SETTING_INPUT_ACTION_LOCATION_FINDER:0 "地点查找器"
 SETTING_INPUT_ACTION_OPEN_POLITICS:0 "政治"
 SETTING_INPUT_ACTION_OPEN_BUDGET:0 "财政"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS:0 "建筑"
 SETTING_INPUT_ACTION_OPEN_MARKET:0 "市场"
 SETTING_INPUT_ACTION_OPEN_MILITARY:0 "军事"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC:0 "外交"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY:0 "科技"
 SETTING_INPUT_ACTION_OPEN_CULTURE:0 "文化"
 SETTING_INPUT_ACTION_OPEN_POPULATION:0 "人口"
 SETTING_INPUT_ACTION_OPEN_JOURNAL:0 "日志"
 SETTING_INPUT_ACTION_OPEN_DECISIONS:0 "决议"
 SETTING_INPUT_ACTION_MAP_LIST:0 "统计报表"
 SETTING_INPUT_ACTION_BACK:0 "后退"
 SETTING_INPUT_ACTION_OPEN_OUTLINER:0 "概览窗口"
 SETTING_INPUT_ACTION_TAB_1:0 "Tab 1"
 SETTING_INPUT_ACTION_TAB_2:0 "Tab 2"
 SETTING_INPUT_ACTION_TAB_3:0 "Tab 3"
 SETTING_INPUT_ACTION_TAB_4:0 "Tab 4"
 SETTING_INPUT_ACTION_TAB_5:0 "Tab 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS:0 "生产视图"
 SETTING_INPUT_ACTION_POLITICAL_LENS:0 "政治视图"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS:0 "外交视图"
 SETTING_INPUT_ACTION_MILITARY_LENS:0 "军事视图"
 SETTING_INPUT_ACTION_TRADE_LENS:0 "贸易视图"
 SETTING_INPUT_ACTION_CONFIRM:0 "确认"
 SETTING_INPUT_ACTION_CURRENT_SITUATION:0 "当前形势"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE:0 "建造队列"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE:0 "暂停/继续建造队列"
 SETTING_INPUT_ACTION_GO_TO_DETAILS:0 "转到详情"
 SETTING_INPUT_ACTION_SCROLL_UP:0 "向上滚动"
 SETTING_INPUT_ACTION_SCROLL_DOWN:0 "向下滚动"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG:0 "(Debug) gui.debug"
