l_korean:
  # DELETE:
    # pm_disabled_gin
    # pm_disabled_elastics
    # pm_masticators
    # pm_rubber_bands
    # pm_luxury_clothes

  # Agriculture Buildings
 pm_primary:0 "주요"
 pmg_secondary_building_rye_farm:0 "보조"
 pmg_secondary_building_wheat_farm:0 "보조"
 pmg_secondary_building_rice_farm:0 "보조"
 pmg_secondary_building_maize_farm:0 "보조"
 pmg_secondary_building_millet_farm:0 "보조"
 pm_no_secondary:0 "단일 작물 유지"
 pm_potatoes:0 "감자"
 pm_vineyards:0 "포도원"
 pm_vineyards_building_maize_farm:0 "포도원"
 pm_apple_orchards:0 "사과 과수원"
 pm_citrus_orchards:0 "감귤 과수원"
 pm_fig_orchards:0 "무화과 과수원"
 pm_mulberry_groves:0 "뽕나무 숲"

 pmg_automation:0 "자동화"
 pmg_automation_building_food_industry:0 "자동화"
 pmg_automation_building_textile_mills:0 "자동화"
 pmg_automation_building_furniture_manufacturies:0 "자동화"
 pmg_automation_building_tooling_workshops:0 "자동화"
 pmg_automation_building_paper_mills:0 "자동화"
 pmg_automation_building_steel_mills:0 "자동화"
 pmg_automation_building_motor_industry:0 "자동화"
 pm_civilian_priority:0 "민간인 우선"
 pm_military_priority:0 "군사 우선"

  # Textile Mills
 pm_craftsman_sewing:0 "수공예 재봉"
 pm_sewing_machines:0 "재봉기"
 pm_electric_sewing_machines:0 "전기 재봉기"
 pm_traditional_looms:0 "전통 베틀"
 pm_mechanized_looms:0 "자동화 베틀"
 pm_automatic_power_looms:0 "자동 역직기"

  # Glassworks
 pm_leaded_glass:0 "납땜 유리"
 pm_manual_glassblowing:0 "수공예 유리 제조"

  # Chemical Plants
 pm_leblanc_process:0 "르블랑 공정"
 pm_no_explosives_production:0 "비료 우선 생산"
 pm_ammonia-soda_process:0 "암모니아 소다법"
 pm_vacuum_evaporation:0 "진공 증발 건조"
 pm_brine_electrolysis:0 "염수 전기분해"
 pmg_fertilizer_production:0 "비료 생산"
 pm_no_artificial_fertilizers:0 "인공 비료 미사용"
 pm_artificial_fertilizers:0 "인공 비료"
 pm_improved_fertilizer:0 "개량형 비료"
 pm_nitrogen_fixation:0 "질소 고정법"
 pm_dyes_production:0 "염료 생산"
 pm_no_synthetic_dyes:0 "합성 염료 미사용"
 pmg_synthetic_dyes:0 "합성 염료"
 pm_silk_production:0 "비단 생산"
 pm_no_artificial_fibers:0 "염료 우선 생산"
 pm_rayon:0 "레이온"

  # Foundries
 pm_steamworks:0 "증기관"
 pm_no_artillery_production:0 "소화기 우선 생산"
 pm_artillery_production:0 "화포 생산"

  # Motor Industries
 pmg_automobile_production:0 "자동차 생산"
 pm_automobile_production:0 "자동차 생산"
