l_braz_por:
 SETTING_INPUT_CONTEXT_COMMON:0 "Comum"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP:1 "Atalhos do teclado para o contexto de comando comum"

 SETTING_INPUT_ACTION_PAUSE:0 "Pausar / Retomar"
 SETTING_INPUT_ACTION_INCREASE_SPEED:0 "Aumentar Velocidade"
 SETTING_INPUT_ACTION_DECREASE_SPEED:0 "Diminuir Velocidade"
 SETTING_INPUT_ACTION_SPEED_ONE:0 "Velocidade 1"
 SETTING_INPUT_ACTION_SPEED_TWO:0 "Velocidade 2"
 SETTING_INPUT_ACTION_SPEED_THREE:0 "Velocidade 3"
 SETTING_INPUT_ACTION_SPEED_FOUR:0 "Velocidade 4"
 SETTING_INPUT_ACTION_SPEED_FIVE:0 "Velocidade 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC:0 "Reproduzir/Pausar Música"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK:0 "Próxima Música"
 SETTING_INPUT_ACTION_CAMERA_UP:0 "Mover a câmera para cima"
 SETTING_INPUT_ACTION_CAMERA_LEFT:0 "Mover a câmera para a esquerda"
 SETTING_INPUT_ACTION_CAMERA_DOWN:0 "Mover a câmera para baixo"
 SETTING_INPUT_ACTION_CAMERA_RIGHT:0 "Mover a câmera para a direita"
 SETTING_INPUT_ACTION_LOCATION_FINDER:0 "Buscador de Local"
 SETTING_INPUT_ACTION_OPEN_POLITICS:0 "Política"
 SETTING_INPUT_ACTION_OPEN_BUDGET:0 "Orçamento"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS:0 "Construções"
 SETTING_INPUT_ACTION_OPEN_MARKET:0 "Mercado"
 SETTING_INPUT_ACTION_OPEN_MILITARY:0 "Militares"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC:0 "Diplomático"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY:0 "Tecnologia"
 SETTING_INPUT_ACTION_OPEN_CULTURE:0 "Cultura"
 SETTING_INPUT_ACTION_OPEN_POPULATION:0 "População"
 SETTING_INPUT_ACTION_OPEN_JOURNAL:0 "Diário"
 SETTING_INPUT_ACTION_OPEN_DECISIONS:0 "Decisões"
 SETTING_INPUT_ACTION_MAP_LIST:0 "Livro-razão"
 SETTING_INPUT_ACTION_BACK:0 "Voltar"
 SETTING_INPUT_ACTION_OPEN_OUTLINER:0 "Destaques"
 SETTING_INPUT_ACTION_TAB_1:0 "Aba 1"
 SETTING_INPUT_ACTION_TAB_2:0 "Aba 2"
 SETTING_INPUT_ACTION_TAB_3:0 "Aba 3"
 SETTING_INPUT_ACTION_TAB_4:0 "Aba 4"
 SETTING_INPUT_ACTION_TAB_5:0 "Aba 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS:0 "Olhar Produtivo"
 SETTING_INPUT_ACTION_POLITICAL_LENS:0 "Olhar Político"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS:0 "Olhar Diplomático"
 SETTING_INPUT_ACTION_MILITARY_LENS:0 "Olhar Militar"
 SETTING_INPUT_ACTION_TRADE_LENS:0 "Olhar Comercial"
 SETTING_INPUT_ACTION_CONFIRM:0 "Confirmar"
 SETTING_INPUT_ACTION_CURRENT_SITUATION:0 "Situação Atual"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE:0 "Fila de Obras"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE:0 "Pausar/Retomar Fila de Obras"
 SETTING_INPUT_ACTION_GO_TO_DETAILS:0 "Ir para Detalhes"
 SETTING_INPUT_ACTION_SCROLL_UP:0 "Rolar para cima"
 SETTING_INPUT_ACTION_SCROLL_DOWN:0 "Rolar para baixo"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG:0 "(Debug) gui.debug"
