l_braz_por:
  # DELETE:
    # pm_disabled_gin
    # pm_disabled_elastics
    # pm_masticators
    # pm_rubber_bands
    # pm_luxury_clothes

  # Agriculture Buildings
 pm_primary:0 "Primário"
 pmg_secondary_building_rye_farm:0 "Secundário"
 pmg_secondary_building_wheat_farm:0 "Secundário"
 pmg_secondary_building_rice_farm:0 "Secundário"
 pmg_secondary_building_maize_farm:0 "Secundário"
 pmg_secondary_building_millet_farm:0 "Secundário"
 pm_no_secondary:0 "Manter Monocultura"
 pm_potatoes:0 "Batatas"
 pm_vineyards:0 "Vinhedos"
 pm_vineyards_building_maize_farm:0 "Vinhedos"
 pm_apple_orchards:0 "Pomares de Maçãs"
 pm_citrus_orchards:0 "Pomares de Cítricos"
 pm_fig_orchards:0 "Pomares de Figos"
 pm_mulberry_groves:0 "Bosques de Amoras"

 pmg_automation:0 "Automação"
 pmg_automation_building_food_industry:0 "Automação"
 pmg_automation_building_textile_mills:0 "Automação"
 pmg_automation_building_furniture_manufacturies:0 "Automação"
 pmg_automation_building_tooling_workshops:0 "Automação"
 pmg_automation_building_paper_mills:0 "Automação"
 pmg_automation_building_steel_mills:0 "Automação"
 pmg_automation_building_motor_industry:0 "Automação"
 pm_civilian_priority:0 "Prioridade Civil"
 pm_military_priority:0 "Prioridade Militar"

  # Textile Mills
 pm_craftsman_sewing:0 "Costura Artesanal"
 pm_sewing_machines:0 "Máquinas de Costura"
 pm_electric_sewing_machines:0 "Máquinas de Costura Elétricas"
 pm_traditional_looms:0 "Teares Tradicionais"
 pm_mechanized_looms:0 "Teares Mecanizados"
 pm_automatic_power_looms:0 "Teares Mecânicos Automáticos"

  # Glassworks
 pm_leaded_glass:0 "Vidro de Chumbo"
 pm_manual_glassblowing:0 "Vidro Soprado Manualmente"

  # Chemical Plants
 pm_leblanc_process:0 "Processo Leblanc"
 pm_no_explosives_production:0 "Priorizar a Produção de Fertilizante"
 pm_ammonia-soda_process:0 "Processo Solvay"
 pm_vacuum_evaporation:0 "Evaporação a Vácuo"
 pm_brine_electrolysis:0 "Eletrólise da Salmoura"
 pmg_fertilizer_production:0 "Produção de Fertilizante"
 pm_no_artificial_fertilizers:0 "Nenhum Fertilizante Artificial"
 pm_artificial_fertilizers:0 "Fertilizantes Artificiais"
 pm_improved_fertilizer:0 "Fertilizantes Melhorados"
 pm_nitrogen_fixation:0 "Processo de Fixação de Nitrogênio"
 pm_dyes_production:0 "Produção de Tinturas"
 pm_no_synthetic_dyes:0 "Nenhuma Tintura Sintética"
 pmg_synthetic_dyes:0 "Tinturas Sintéticas"
 pm_silk_production:0 "Produção de Seda"
 pm_no_artificial_fibers:0 "Priorizar a Produção de Tintura"
 pm_rayon:0 "Rayon"

  # Foundries
 pm_steamworks:0 "A Vapor"
 pm_no_artillery_production:0 "Priorizar a Produção de Armas Leves"
 pm_artillery_production:0 "Produção de Artilharia"

  # Motor Industries
 pmg_automobile_production:0 "Produção de Automóveis"
 pm_automobile_production:0 "Produção de Automóveis"
