l_braz_por:
 SETTING_AUTOSAVE_TO_CLOUD:0 "Salvamento automático na nuvem"
 SETTING_SAVE_FILE_FORMAT:0 "Formato de salvamento padrão"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP:0 "Esta opção é anulada nos modos Ironman, Nuvem e Debug"
 OPTION_SAVE_FILE_TEXT:0 "Texto"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL:0 "Texto compactado"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL:0 "Binário compactado"
 SETTING_TOOLTIP_MODE:0 "Modo Dicas de Contexto"
 SETTING_TOOLTIP_MODE_TOOLTIP:1 "#T $SETTING_TOOLTIP_MODE$#!\nEscolha como as dicas de contexto devem ficar travadas:\n   #b Tendência do Mouse#! - Trava se o mouse for movido em direção à dica de contexto.\n   #b Travamento por Tempo#! - Trava após um tempo predeterminado.\n   #b Travamento por Ação#! - Trava com o botão do meio do mouse."
 SETTING_TOOLTIP_MODE_NO_LOCK:0 "Sem bloqueio"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Tendência do Mouse"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR:0 "Travamento por Ação (Ancoragem do Mouse)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR:0 "Travamento por Tempo (Ancoragem do Mouse)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR:0 "Travamento por Ação"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR:0 "Travamento por Tempo"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nDefine o atraso antes da dica de contexto aparecer, ao passar o cursor sobre um elemento com dica de contexto."
 SETTING_TOOLTIP_DELAY:0 "Mostrar Atraso"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Desbloquear Atraso"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nDefine o atraso até as dicas de contexto serem desbloqueadas."
 SETTING_TOOLTIP_LOCK_TIME:0 "Bloquear Atraso"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nDefine o atraso até as dicas de contexto serem bloqueadas."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Atraso Aberto Bloqueado"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nDefine o atraso até as dicas de contexto serem bloqueadas quando outras já estão abertas."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Avançado"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Geral"
 SETTINGS_CATEGORY_SFX:0 "Efeitos de Som Específicos"
 SETTINGS_CATEGORY_LANGUAGE:0 "Idioma"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Jogos Salvos"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Configuração das Dicas de Contexto"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Controles do Mapa"
 SETTING_SHADER_QUALITY:0 "Qualidade de Sombreamento"
 SETTING_SHADER_QUALITY_TOOLTIP:1 "#T Qualidade de Sombreamento\n#!Determina a qualidade de diversos efeitos e do sombreamento.\n\n#T Alta:#! melhora a qualidade de alguns efeitos de sombreamento em detrimento do desempenho.\n\n#T Média:#! configuração padrão para a experiência gráfica pretendida.\n\n#T Baixa:#! configuração destinada a máquinas de baixo desempenho e não recomendada devido à perda de qualidade gráfica. Diversos sombreamentos são simplificados para impulsionar o desempenho."
 SETTING_SHOW_NUDITY:0 "Mostrar nudez"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nDefine se os personagens podem aparecer nus."
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Retratos"
  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC:0 "Música"
 SETTING_AMBIENT:0 "Ambiente"
 SETTING_MUSIC_TOOLTIP:0 "#T Volume da Música\n#!Define o volume da música."
 SETTING_AMBIENT_TOOLTIP:0 "#T Volume Ambiente\n#!Define o volume do som ambiente."

 color_blind_mode_test:0 "Testar"
