l_turkish:
 SETTING_INPUT_CONTEXT_COMMON:0 "Yaygın"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP:1 "Yaygın girdilerin tuş atamaları"

 SETTING_INPUT_ACTION_PAUSE:0 "Durdur / Devam Ettir"
 SETTING_INPUT_ACTION_INCREASE_SPEED:0 "Hızı Arttır"
 SETTING_INPUT_ACTION_DECREASE_SPEED:0 "Hızı Düşür"
 SETTING_INPUT_ACTION_SPEED_ONE:0 "1. Hız"
 SETTING_INPUT_ACTION_SPEED_TWO:0 "2. Hız"
 SETTING_INPUT_ACTION_SPEED_THREE:0 "3. Hız"
 SETTING_INPUT_ACTION_SPEED_FOUR:0 "4. Hız"
 SETTING_INPUT_ACTION_SPEED_FIVE:0 "5. Hız"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC:0 "Müziği Çal/Duraksat"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK:0 "Sonraki şarkı"
 SETTING_INPUT_ACTION_CAMERA_UP:0 "Kamerayı Yukarı Kaydır"
 SETTING_INPUT_ACTION_CAMERA_LEFT:0 "Kamerayı Sola Kaydır"
 SETTING_INPUT_ACTION_CAMERA_DOWN:0 "Kamerayı Aşağı Kaydır"
 SETTING_INPUT_ACTION_CAMERA_RIGHT:0 "Kamerayı Sağa Kaydır"
 SETTING_INPUT_ACTION_LOCATION_FINDER:0 "Konum Bulucu"
 SETTING_INPUT_ACTION_OPEN_POLITICS:0 "Siyaset"
 SETTING_INPUT_ACTION_OPEN_BUDGET:0 "Bütçe"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS:0 "Binalar"
 SETTING_INPUT_ACTION_OPEN_MARKET:0 "Pazar"
 SETTING_INPUT_ACTION_OPEN_MILITARY:0 "Ordu"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC:0 "Diplomatik"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY:0 "Teknoloji"
 SETTING_INPUT_ACTION_OPEN_CULTURE:0 "Kültür"
 SETTING_INPUT_ACTION_OPEN_POPULATION:0 "Nüfus"
 SETTING_INPUT_ACTION_OPEN_JOURNAL:0 "Günlük"
 SETTING_INPUT_ACTION_OPEN_DECISIONS:0 "Kararlar"
 SETTING_INPUT_ACTION_MAP_LIST:0 "Defter"
 SETTING_INPUT_ACTION_BACK:0 "Geri"
 SETTING_INPUT_ACTION_OPEN_OUTLINER:0 "Yan Bilgi"
 SETTING_INPUT_ACTION_TAB_1:0 "1. Sekme"
 SETTING_INPUT_ACTION_TAB_2:0 "2. Sekme"
 SETTING_INPUT_ACTION_TAB_3:0 "3. Sekme"
 SETTING_INPUT_ACTION_TAB_4:0 "4. Sekme"
 SETTING_INPUT_ACTION_TAB_5:0 "5. Sekme"
 SETTING_INPUT_ACTION_PRODUCTION_LENS:0 "Üretim Görünümü"
 SETTING_INPUT_ACTION_POLITICAL_LENS:0 "Siyasi Görünüm"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS:0 "Diplomatik Görünüm"
 SETTING_INPUT_ACTION_MILITARY_LENS:0 "Askeri Görünüm"
 SETTING_INPUT_ACTION_TRADE_LENS:0 "Ticari Görünüm"
 SETTING_INPUT_ACTION_CONFIRM:0 "Onayla"
 SETTING_INPUT_ACTION_CURRENT_SITUATION:0 "Mevcut Durum"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE:0 "İnşa Sırası"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE:0 "İnşa Sırasını Durdur/Devam Ettir"
 SETTING_INPUT_ACTION_GO_TO_DETAILS:0 "Ayrıntılara Git"
 SETTING_INPUT_ACTION_SCROLL_UP:0 "Yukarı kaydır"
 SETTING_INPUT_ACTION_SCROLL_DOWN:0 "Aşağı kaydır"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG:0 "(Hata Ayıklama) gui.debug"
