l_turkish:
  # DELETE:
    # pm_disabled_gin
    # pm_disabled_elastics
    # pm_masticators
    # pm_rubber_bands
    # pm_luxury_clothes

  # Agriculture Buildings
 pm_primary:0 "Ana"
 pmg_secondary_building_rye_farm:0 "İkincil"
 pmg_secondary_building_wheat_farm:0 "İkincil"
 pmg_secondary_building_rice_farm:0 "İkincil"
 pmg_secondary_building_maize_farm:0 "İkincil"
 pmg_secondary_building_millet_farm:0 "İkincil"
 pm_no_secondary:0 "Tek Ürün Yetiştir"
 pm_potatoes:0 "Patates"
 pm_vineyards:0 "Üzüm Bağları"
 pm_vineyards_building_maize_farm:0 "Üzüm Bağları"
 pm_apple_orchards:0 "Elma Bahçeleri"
 pm_citrus_orchards:0 "Narenciye Bahçeleri"
 pm_fig_orchards:0 "İncir Bahçeleri"
 pm_mulberry_groves:0 "Dut Koruları"

 pmg_automation:0 "Otomasyon"
 pmg_automation_building_food_industry:0 "Otomasyon"
 pmg_automation_building_textile_mills:0 "Otomasyon"
 pmg_automation_building_furniture_manufacturies:0 "Otomasyon"
 pmg_automation_building_tooling_workshops:0 "Otomasyon"
 pmg_automation_building_paper_mills:0 "Otomasyon"
 pmg_automation_building_steel_mills:0 "Otomasyon"
 pmg_automation_building_motor_industry:0 "Otomasyon"
 pm_civilian_priority:0 "Sivil Öncelik"
 pm_military_priority:0 "Askeri Öncelik"

  # Textile Mills
 pm_craftsman_sewing:0 "El Dikişi"
 pm_sewing_machines:0 "Dikiş Makineleri"
 pm_electric_sewing_machines:0 "Elektrikli Dikiş Makineleri"
 pm_traditional_looms:0 "Geleneksel Dokuma Tezgâhları"
 pm_mechanized_looms:0 "Mekanize Dokuma Tezgâhları"
 pm_automatic_power_looms:0 "Otomatik Elektrikli Dokuma Tezgâhları"

  # Glassworks
 pm_leaded_glass:0 "Kristal Cam"
 pm_manual_glassblowing:0 "Elle Cam Üfleme"

  # Chemical Plants
 pm_leblanc_process:0 "Leblanc İşlemi"
 pm_no_explosives_production:0 "Gübre Üretimi Önceliği"
 pm_ammonia-soda_process:0 "Amonyak-soda İşlemi"
 pm_vacuum_evaporation:0 "Vakumlu Buharlaşma"
 pm_brine_electrolysis:0 "Tuzlu Su Elektrolizi"
 pmg_fertilizer_production:0 "Gübre Üretimi"
 pm_no_artificial_fertilizers:0 "Suni Gübre Yok"
 pm_artificial_fertilizers:0 "Suni Gübreler"
 pm_improved_fertilizer:0 "Geliştirilmiş Gübreler"
 pm_nitrogen_fixation:0 "Azot Bağlama İşlemi"
 pm_dyes_production:0 "Boya Üretimi"
 pm_no_synthetic_dyes:0 "Sentetik Boya Yok"
 pmg_synthetic_dyes:0 "Sentetik Boya"
 pm_silk_production:0 "İpek Üretimi"
 pm_no_artificial_fibers:0 "Boya Üretimi Önceliği"
 pm_rayon:0 "Rayon"

  # Foundries
 pm_steamworks:0 "Buharlı Makineler"
 pm_no_artillery_production:0 "Hafif Silah Üretimi Önceliği"
 pm_artillery_production:0 "Top Üretimi"

  # Motor Industries
 pmg_automobile_production:0 "Otomobil Üretimi"
 pm_automobile_production:0 "Otomobil Üretimi"
