l_french:
 SETTING_INPUT_CONTEXT_COMMON:0 "Commun"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP:1 "Raccourcis clavier pour le contexte d’entrée commun"

 SETTING_INPUT_ACTION_PAUSE:0 "Pause / Reprendre"
 SETTING_INPUT_ACTION_INCREASE_SPEED:0 "Augmenter la vitesse"
 SETTING_INPUT_ACTION_DECREASE_SPEED:0 "Diminuer la vitesse"
 SETTING_INPUT_ACTION_SPEED_ONE:0 "Vitesse 1"
 SETTING_INPUT_ACTION_SPEED_TWO:0 "Vitesse 2"
 SETTING_INPUT_ACTION_SPEED_THREE:0 "Vitesse 3"
 SETTING_INPUT_ACTION_SPEED_FOUR:0 "Vitesse 4"
 SETTING_INPUT_ACTION_SPEED_FIVE:0 "Vitesse 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC:0 "Lire/mettre en pause la musique"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK:0 "Piste musicale suivante"
 SETTING_INPUT_ACTION_CAMERA_UP:0 "Panoramique vers le haut"
 SETTING_INPUT_ACTION_CAMERA_LEFT:0 "Panoramique vers la gauche"
 SETTING_INPUT_ACTION_CAMERA_DOWN:0 "Panoramique vers le bas"
 SETTING_INPUT_ACTION_CAMERA_RIGHT:0 "Panoramique vers la droite"
 SETTING_INPUT_ACTION_LOCATION_FINDER:0 "Recherche de lieux"
 SETTING_INPUT_ACTION_OPEN_POLITICS:0 "Politique"
 SETTING_INPUT_ACTION_OPEN_BUDGET:0 "Budget"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS:0 "Bâtiments"
 SETTING_INPUT_ACTION_OPEN_MARKET:0 "Marché"
 SETTING_INPUT_ACTION_OPEN_MILITARY:0 "Militaire"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC:0 "Diplomatique"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY:0 "Technologie"
 SETTING_INPUT_ACTION_OPEN_CULTURE:0 "Culture"
 SETTING_INPUT_ACTION_OPEN_POPULATION:0 "Population"
 SETTING_INPUT_ACTION_OPEN_JOURNAL:0 "Journal"
 SETTING_INPUT_ACTION_OPEN_DECISIONS:0 "Décisions"
 SETTING_INPUT_ACTION_MAP_LIST:0 "Registre"
 SETTING_INPUT_ACTION_BACK:0 "Retour"
 SETTING_INPUT_ACTION_OPEN_OUTLINER:0 "Tableau de bord"
 SETTING_INPUT_ACTION_TAB_1:0 "Onglet 1"
 SETTING_INPUT_ACTION_TAB_2:0 "Onglet 2"
 SETTING_INPUT_ACTION_TAB_3:0 "Onglet 3"
 SETTING_INPUT_ACTION_TAB_4:0 "Onglet 4"
 SETTING_INPUT_ACTION_TAB_5:0 "Onglet 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS:0 "Aperçu de la production"
 SETTING_INPUT_ACTION_POLITICAL_LENS:0 "Aperçu politique"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS:0 "Aperçu diplomatique"
 SETTING_INPUT_ACTION_MILITARY_LENS:0 "Aperçu militaire"
 SETTING_INPUT_ACTION_TRADE_LENS:0 "Aperçu du commerce"
 SETTING_INPUT_ACTION_CONFIRM:0 "Confirmer"
 SETTING_INPUT_ACTION_CURRENT_SITUATION:0 "Situation actuelle"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE:0 "File d’attente de construction"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE:0 "Mettre en pause/Rétablir la file d’attente de construction"
 SETTING_INPUT_ACTION_GO_TO_DETAILS:0 "Aller à l’écran Détails"
 SETTING_INPUT_ACTION_SCROLL_UP:0 "Faire défiler vers le haut"
 SETTING_INPUT_ACTION_SCROLL_DOWN:0 "Faire défiler vers le bas"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG:0 "(Debug) gui.debug"
