l_french:
 SETTING_INPUT_CONTEXT_COMMON:0 "Commun"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP:0 "#todo Raccourcis clavier pour le contexte d’entrée commun#!"

 SETTING_INPUT_ACTION_PAUSE:0 "Pause / Reprendre"
 SETTING_INPUT_ACTION_INCREASE_SPEED:0 "Augmenter la vitesse"
 SETTING_INPUT_ACTION_DECREASE_SPEED:0 "Diminuer la vitesse"
 SETTING_INPUT_ACTION_SPEED_ONE:0 "Vitesse 1"
 SETTING_INPUT_ACTION_SPEED_TWO:0 "Vitesse 2"
 SETTING_INPUT_ACTION_SPEED_THREE:0 "Vitesse 3"
 SETTING_INPUT_ACTION_SPEED_FOUR:0 "Vitesse 4"
 SETTING_INPUT_ACTION_SPEED_FIVE:0 "Vitesse 5"
 SETTING_INPUT_ACTION_CAMERA_UP:0 "Panoramique vers le haut"
 SETTING_INPUT_ACTION_CAMERA_LEFT:0 "Panoramique vers la gauche"
 SETTING_INPUT_ACTION_CAMERA_DOWN:0 "Panoramique vers le bas"
 SETTING_INPUT_ACTION_CAMERA_RIGHT:0 "Panoramique vers la droite"
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_LOCATION_FINDER`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_OPEN_POLITICS`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_OPEN_BUDGET`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_OPEN_BUILDINGS`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_OPEN_MARKET`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_OPEN_MILITARY`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_OPEN_DIPLOMATIC`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_OPEN_TECHNOLOGY`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_OPEN_CULTURE`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_OPEN_POPULATION`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_OPEN_JOURNAL`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_OPEN_DECISIONS`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_MAP_LIST`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_BACK`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_OPEN_OUTLINER`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_TAB_1`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_TAB_2`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_TAB_3`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_TAB_4`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_TAB_5`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_PRODUCTION_LENS`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_POLITICAL_LENS`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_DIPLOMATIC_LENS`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_MILITARY_LENS`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_TRADE_LENS`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_CONFIRM`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_CURRENT_SITUATION`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_GO_TO_DETAILS`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_SCROLL_UP`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_SCROLL_DOWN`
 # [LocEditor:UntranslatedKey] `SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG`
