l_french:
  # DELETE:
    # pm_disabled_gin
    # pm_disabled_elastics
    # pm_masticators
    # pm_rubber_bands
    # pm_luxury_clothes

  # Agriculture Buildings
 pm_primary:0 "Principale"
 pmg_secondary_building_rye_farm:0 "Secondaire"
 pmg_secondary_building_wheat_farm:0 "Secondaire"
 pmg_secondary_building_rice_farm:0 "Secondaire"
 pmg_secondary_building_maize_farm:0 "Secondaire"
 pmg_secondary_building_millet_farm:0 "Secondaire"
 pm_no_secondary:0 "Maintien d’une culture unique"
 pm_potatoes:0 "Pommes de terre"
 pm_vineyards:0 "Vignobles"
 pm_vineyards_building_maize_farm:0 "Vignobles"
 pm_apple_orchards:0 "Pommeraies"
 pm_citrus_orchards:0 "Plantations d’agrumes"
 pm_fig_orchards:0 "Figueraies"
 pm_mulberry_groves:0 "Mûreraies"

 pmg_automation:0 "Automatisation"
 pmg_automation_building_food_industry:0 "Automatisation"
 pmg_automation_building_textile_mills:0 "Automatisation"
 pmg_automation_building_furniture_manufacturies:0 "Automatisation"
 pmg_automation_building_tooling_workshops:0 "Automatisation"
 pmg_automation_building_paper_mills:0 "Automatisation"
 pmg_automation_building_steel_mills:0 "Automatisation"
 pmg_automation_building_motor_industry:0 "Automatisation"
 pm_civilian_priority:0 "Priorité civile"
 pm_military_priority:0 "Priorité militaire"

  # Textile Mills
 pm_craftsman_sewing:0 "Couture artisanale"
 pm_sewing_machines:0 "Machines à coudre"
 pm_electric_sewing_machines:0 "Machines à coudre électriques"
 pm_traditional_looms:0 "Métiers à tisser traditionnels"
 pm_mechanized_looms:0 "Métiers à tisser mécanisés"
 pm_automatic_power_looms:0 "Métiers à tisser mécaniques automatiques"

  # Glassworks
 pm_leaded_glass:0 "Verre plombé"
 pm_manual_glassblowing:0 "Soufflage du verre artisanal"

  # Chemical Plants
 pm_leblanc_process:0 "Procédé Leblanc"
 pm_no_explosives_production:0 "Prioriser la production d’engrais"
 pm_ammonia-soda_process:0 "Procédé Solvay"
 pm_vacuum_evaporation:0 "Évaporation sous vide"
 pm_brine_electrolysis:0 "Électrolyse de saumure"
 pmg_fertilizer_production:0 "Production d’engrais"
 pm_no_artificial_fertilizers:0 "Aucun engrais artificiel"
 pm_artificial_fertilizers:0 "Engrais artificiels"
 pm_improved_fertilizer:0 "Engrais améliorés"
 pm_nitrogen_fixation:0 "Procédé de fixation de l’azote"
 pm_dyes_production:0 "Production de colorants"
 pm_no_synthetic_dyes:0 "Aucun colorant synthétique"
 pmg_synthetic_dyes:0 "Colorants synthétiques"
 pm_silk_production:0 "Production de soie"
 pm_no_artificial_fibers:0 "Prioriser la production de colorants"
 pm_rayon:0 "Soie artificielle"

  # Foundries
 pm_steamworks:0 "Machines à vapeur"
 pm_no_artillery_production:0 "Prioriser la production d’armes légères"
 pm_artillery_production:0 "Production d’artillerie"

  # Motor Industries
 pmg_automobile_production:0 "Production automobile"
 pm_automobile_production:0 "Production automobile"
