l_french:
 SETTING_AUTOSAVE_TO_CLOUD:0 "Sauvegarde auto sur le Cloud"
 SETTING_SAVE_FILE_FORMAT:0 "Format de sauvegarde par défaut"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP:0 "Cette option est ignorée en mode Ironman, Cloud et Debug"
 OPTION_SAVE_FILE_TEXT:0 "Texte"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL:0 "Texte condensé"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL:0 "Binaire condensé"
 SETTING_TOOLTIP_MODE:0 "Mode infobulle"
 SETTING_TOOLTIP_MODE_TOOLTIP:1 "#T $SETTING_TOOLTIP_MODE$#!\nComment les infobulles doivent se verrouiller ?\n   #b Selon la souris#! - se verrouille si vous déplacez la souris vers l’infobulle.\n   #b Selon le temps#! - se verrouille après un temps défini.\n   #b Selon l’action#! - se verrouille via le bouton central de la souris."
 SETTING_TOOLTIP_MODE_NO_LOCK:0 "Pas de verrouillage"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Selon la souris"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR:0 "Verrouillage de l’action (ancrage souris)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR:0 "Verrouillage du temps (ancrage souris)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR:0 "Selon l’action"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR:0 "Selon le temps"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nDéfinit le délai avant que l’infobulle n’apparaisse lors du survol d’un élément avec une infobulle."
 SETTING_TOOLTIP_DELAY:0 "Afficher le délai"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Délai de déverrouillage"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nDéfinit le délai avant le déverrouillage des infobulles."
 SETTING_TOOLTIP_LOCK_TIME:0 "Délai de verrouillage"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nDéfinit le délai avant le verrouillage des infobulles."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Délai de verrouillage si ouvert"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nDéfinit le délai avant le verrouillage des infobulles lorsqu’une autre infobulle est déjà ouverte."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Avancé"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Général"
 SETTINGS_CATEGORY_SFX:0 "Effets sonores spécifiques"
 SETTINGS_CATEGORY_LANGUAGE:0 "Langue"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Sauvegardes"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Paramètres des infobulles"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Contrôles de carte"
 SETTING_SHADER_QUALITY:0 "Qualité des nuanceurs"
 SETTING_SHADER_QUALITY_TOOLTIP:1 "#T Qualité des nuanceurs\n#!Permet de régler la qualité des différents effets et nuanceurs.\n\n#T Élevée :#! améliore la qualité des nuanceurs, mais réduit les performances.\n\n#T Moyenne :#! paramètres par défaut pour des graphismes optimaux.\n\n#T Faible :#! plusieurs nuanceurs sont simplifiés afin de réduire la qualité des graphismes et d’améliorer les performances pour les machines moins puissantes."
 SETTING_SHOW_NUDITY:0 "Afficher la nudité"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nDéfinit si les personnages peuvent être affichés nus."
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Portraits"
  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC:0 "Musique"
 SETTING_AMBIENT:0 "Ambiance"
 SETTING_MUSIC_TOOLTIP:0 "#T Volume de la musique\n#!Permet de régler le volume de la musique."
 SETTING_AMBIENT_TOOLTIP:0 "#T Volume d’ambiance\n#!Permet de régler le volume des sons d’ambiance."

 color_blind_mode_test:0 "Test"
