l_german:
 SETTING_INPUT_CONTEXT_COMMON:0 "Üblich"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP:1 "Tastaturbelegungen für übliche Kontexteingaben"

 SETTING_INPUT_ACTION_PAUSE:0 "Pause / Beenden"
 SETTING_INPUT_ACTION_INCREASE_SPEED:0 "Tempo erhöhen"
 SETTING_INPUT_ACTION_DECREASE_SPEED:0 "Tempo senken"
 SETTING_INPUT_ACTION_SPEED_ONE:0 "Tempo 1"
 SETTING_INPUT_ACTION_SPEED_TWO:0 "Tempo 2"
 SETTING_INPUT_ACTION_SPEED_THREE:0 "Tempo 3"
 SETTING_INPUT_ACTION_SPEED_FOUR:0 "Tempo 4"
 SETTING_INPUT_ACTION_SPEED_FIVE:0 "Tempo 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC:0 "Musik spielen/pausieren"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK:0 "Nächster Musiktitel"
 SETTING_INPUT_ACTION_CAMERA_UP:0 "Kamera nach oben schwenken"
 SETTING_INPUT_ACTION_CAMERA_LEFT:0 "Kamera nach links schwenken"
 SETTING_INPUT_ACTION_CAMERA_DOWN:0 "Kamera nach unten schwenken"
 SETTING_INPUT_ACTION_CAMERA_RIGHT:0 "Kamera nach rechts schwenken"
 SETTING_INPUT_ACTION_LOCATION_FINDER:0 "Ortsfinder"
 SETTING_INPUT_ACTION_OPEN_POLITICS:0 "Politik"
 SETTING_INPUT_ACTION_OPEN_BUDGET:0 "Etat"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS:0 "Gebäude"
 SETTING_INPUT_ACTION_OPEN_MARKET:0 "Markt"
 SETTING_INPUT_ACTION_OPEN_MILITARY:0 "Militär"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC:0 "Diplomatisch"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY:0 "Technik"
 SETTING_INPUT_ACTION_OPEN_CULTURE:0 "Kultur"
 SETTING_INPUT_ACTION_OPEN_POPULATION:0 "Bevölkerung"
 SETTING_INPUT_ACTION_OPEN_JOURNAL:0 "Journal"
 SETTING_INPUT_ACTION_OPEN_DECISIONS:0 "Entscheidungen"
 SETTING_INPUT_ACTION_MAP_LIST:0 "Hauptbuch"
 SETTING_INPUT_ACTION_BACK:0 "Zurück"
 SETTING_INPUT_ACTION_OPEN_OUTLINER:0 "Pinnwand"
 SETTING_INPUT_ACTION_TAB_1:0 "Reiter 1"
 SETTING_INPUT_ACTION_TAB_2:0 "Reiter 2"
 SETTING_INPUT_ACTION_TAB_3:0 "Reiter 3"
 SETTING_INPUT_ACTION_TAB_4:0 "Reiter 4"
 SETTING_INPUT_ACTION_TAB_5:0 "Reiter 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS:0 "Produktionslinse"
 SETTING_INPUT_ACTION_POLITICAL_LENS:0 "Politiklinse"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS:0 "Diplomatielinse"
 SETTING_INPUT_ACTION_MILITARY_LENS:0 "Militärlinse"
 SETTING_INPUT_ACTION_TRADE_LENS:0 "Handelslinse"
 SETTING_INPUT_ACTION_CONFIRM:0 "Bestätigen"
 SETTING_INPUT_ACTION_CURRENT_SITUATION:0 "Derzeitige Lage"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE:0 "Baureihe"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE:0 "Baureihe pausieren/wieder starten"
 SETTING_INPUT_ACTION_GO_TO_DETAILS:0 "Zu Details gehen"
 SETTING_INPUT_ACTION_SCROLL_UP:0 "Nach oben scrollen"
 SETTING_INPUT_ACTION_SCROLL_DOWN:0 "Nach unten scrollen"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG:0 "(Debug) gui.debug"
