l_german:
  # DELETE:
    # pm_disabled_gin
    # pm_disabled_elastics
    # pm_masticators
    # pm_rubber_bands
    # pm_luxury_clothes

  # Agriculture Buildings
 pm_primary:0 "Primär"
 pmg_secondary_building_rye_farm:0 "Sekundär"
 pmg_secondary_building_wheat_farm:0 "Sekundär"
 pmg_secondary_building_rice_farm:0 "Sekundär"
 pmg_secondary_building_maize_farm:0 "Sekundär"
 pmg_secondary_building_millet_farm:0 "Sekundär"
 pm_no_secondary:0 "Gleichbleibende Feldfrucht behalten"
 pm_potatoes:0 "Kartoffeln"
 pm_vineyards:0 "Weinberge"
 pm_vineyards_building_maize_farm:0 "Weinberge"
 pm_apple_orchards:0 "Apfelhaine"
 pm_citrus_orchards:0 "Zitrushaine"
 pm_fig_orchards:0 "Feigenhaine"
 pm_mulberry_groves:0 "Maulbeerhaine"

 pmg_automation:0 "Automation"
 pmg_automation_building_food_industry:0 "Automation"
 pmg_automation_building_textile_mills:0 "Automation"
 pmg_automation_building_furniture_manufacturies:0 "Automation"
 pmg_automation_building_tooling_workshops:0 "Automation"
 pmg_automation_building_paper_mills:0 "Automation"
 pmg_automation_building_steel_mills:0 "Automation"
 pmg_automation_building_motor_industry:0 "Automation"
 pm_civilian_priority:0 "Zivilpriorität"
 pm_military_priority:0 "Militärpriorität"

  # Textile Mills
 pm_craftsman_sewing:0 "Handnäharbeit"
 pm_sewing_machines:0 "Nähmaschinen"
 pm_electric_sewing_machines:0 "Elektrische Nähmaschinen"
 pm_traditional_looms:0 "Traditionelle Webstühle"
 pm_mechanized_looms:0 "Webmaschinen"
 pm_automatic_power_looms:0 "Automatische Webmaschinen"

  # Glassworks
 pm_leaded_glass:0 "Bleiglas"
 pm_manual_glassblowing:0 "Manuelle Glasbläser"

  # Chemical Plants
 pm_leblanc_process:0 "Leblanc-Verfahren"
 pm_no_explosives_production:0 "Vorrang für Düngerproduktion"
 pm_ammonia-soda_process:0 "Ammoniak-Soda-Verfahren"
 pm_vacuum_evaporation:0 "Vakuumverdampfung"
 pm_brine_electrolysis:0 "Salzwasser-Elektrolyse"
 pmg_fertilizer_production:0 "Düngerproduktion"
 pm_no_artificial_fertilizers:0 "Kein Kunstdünger"
 pm_artificial_fertilizers:0 "Kunstdünger"
 pm_improved_fertilizer:0 "Verbesserter Dünger"
 pm_nitrogen_fixation:0 "Stickstofffixierungsverfahren"
 pm_dyes_production:0 "Färbemittel-Produktion"
 pm_no_synthetic_dyes:0 "Keine synthetischen Färbemittel"
 pmg_synthetic_dyes:0 "Synthetische Färbemittel"
 pm_silk_production:0 "Seiden-Produktion"
 pm_no_artificial_fibers:0 "Vorrang für Färbemittel-Produktion"
 pm_rayon:0 "Rayon"

  # Foundries
 pm_steamworks:0 "Dampfwerke"
 pm_no_artillery_production:0 "Vorrang für Handfeuerwaffen-Produktion"
 pm_artillery_production:0 "Artillerie-Produktion"

  # Motor Industries
 pmg_automobile_production:0 "Automobil-Produktion"
 pm_automobile_production:0 "Automobil-Produktion"
