l_german:
 SETTING_AUTOSAVE_TO_CLOUD:0 "In Cloud autospeichern"
 SETTING_SAVE_FILE_FORMAT:0 "Standard-Speicherformat"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP:0 "Diese Option wird im Ironman-, Cloud- und Debug-Modus überschrieben"
 OPTION_SAVE_FILE_TEXT:0 "Text"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL:0 "Gezippter Text"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL:0 "Gezipptes Binary"
 SETTING_TOOLTIP_MODE:0 "Tooltip-Modus"
 SETTING_TOOLTIP_MODE_TOOLTIP:1 "#T $SETTING_TOOLTIP_MODE$#!\nLegt fest, wie die Tooltip-Locks aktiviert werden:\n   #b Maustendenz#! – Wird aktiviert, wenn man die Maus auf den Tooltip zubewegt.\n   #b Timer-Lock#! – Wird nach einer bestimmten Frist aktiviert.\n   #b Aktions-Lock#! – Wird mit der mittleren Maustaste aktiviert."
 SETTING_TOOLTIP_MODE_NO_LOCK:0 "Kein Lock"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Maustendenz"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR:0 "Aktions-Lock (Mausanker)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR:0 "Timer-Lock (Mausanker)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR:0 "Aktions-Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR:0 "Timer-Lock"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nLegt die Verzögerung fest, ehe der Tooltip angezeigt wird, wenn der Mauszeiger auf einem Element mit Tooltip ist."
 SETTING_TOOLTIP_DELAY:0 "Verzögerung anzeigen"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Freischaltungsverzögerung"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nLegt die Verzögerung fest, bis Tooltips freigeschaltet werden."
 SETTING_TOOLTIP_LOCK_TIME:0 "Lock-Verzögerung"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nLegt die Verzögerung fest, bis Tooltips verriegelt werden."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Lock-Öffnungsverzögerung"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nLegt die Verzögerung fest, bis Tooltips verriegelt werden, während ein anderer Tooltip geöffnet ist."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Fortgeschritten"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Allgemein"
 SETTINGS_CATEGORY_SFX:0 "Spezifische Soundeffekte"
 SETTINGS_CATEGORY_LANGUAGE:0 "Sprache"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Spielstände"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Tooltip-Einstellungen"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Kartensteuerung"
 SETTING_SHADER_QUALITY:0 "Shader-Qualität"
 SETTING_SHADER_QUALITY_TOOLTIP:1 "#T Shader-Qualität\n#!Bestimmt die Qualität verschiedener Shader und Effekte.\n\n#T Hoch:#! Verbessert die Qualität einiger Shader-Effekte auf Kosten der Leistung.\n\n#T Mittel:#! Standardeinstellung für die intendierte Grafikerfahrung.\n\n#T Niedrig:#! Diese Einstellung ist für Low-End-Computer gedacht und wird aufgrund des Verlusts an visueller Qualität nicht empfohlen. Eine Reihe von Shadern wird vereinfacht, um die Grafikleistung zu verbessern."
 SETTING_SHOW_NUDITY:0 "Nacktheit anzeigen"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nLegt fest, ob Charaktere nackt gezeigt werden können."
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Porträts"
  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC:0 "Musik"
 SETTING_AMBIENT:0 "Umgebung"
 SETTING_MUSIC_TOOLTIP:0 "#T Musiklautstärke\n#!Steuert die Lautstärke der Hintergrundmusik."
 SETTING_AMBIENT_TOOLTIP:0 "#T Umgebungslautstärke\n#!Steuert die Lautstärke der Umgebungsatmosphäre."

 color_blind_mode_test:0 "Test"
