l_spanish:
 SETTING_INPUT_CONTEXT_COMMON:0 "Común"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP:1 "Combinaciones de teclas para contexto de entrada común"

 SETTING_INPUT_ACTION_PAUSE:0 "Pausar/Reanudar"
 SETTING_INPUT_ACTION_INCREASE_SPEED:0 "Aumentar la velocidad"
 SETTING_INPUT_ACTION_DECREASE_SPEED:0 "Reducir la velocidad"
 SETTING_INPUT_ACTION_SPEED_ONE:0 "Velocidad 1"
 SETTING_INPUT_ACTION_SPEED_TWO:0 "Velocidad 2"
 SETTING_INPUT_ACTION_SPEED_THREE:0 "Velocidad 3"
 SETTING_INPUT_ACTION_SPEED_FOUR:0 "Velocidad 4"
 SETTING_INPUT_ACTION_SPEED_FIVE:0 "Velocidad 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC:0 "Reproducir/Pausar la música"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK:0 "Siguiente pista de música"
 SETTING_INPUT_ACTION_CAMERA_UP:0 "Desplazar cámara hacia arriba"
 SETTING_INPUT_ACTION_CAMERA_LEFT:0 "Desplazar cámara a la izquierda"
 SETTING_INPUT_ACTION_CAMERA_DOWN:0 "Desplazar cámara hacia abajo"
 SETTING_INPUT_ACTION_CAMERA_RIGHT:0 "Desplazar cámara a la derecha"
 SETTING_INPUT_ACTION_LOCATION_FINDER:0 "Buscador de ubicaciones"
 SETTING_INPUT_ACTION_OPEN_POLITICS:0 "Política"
 SETTING_INPUT_ACTION_OPEN_BUDGET:0 "Presupuesto"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS:0 "Edificios"
 SETTING_INPUT_ACTION_OPEN_MARKET:0 "Mercado"
 SETTING_INPUT_ACTION_OPEN_MILITARY:0 "Ejército"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC:0 "Diplomacia"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY:0 "Tecnología"
 SETTING_INPUT_ACTION_OPEN_CULTURE:0 "Cultura"
 SETTING_INPUT_ACTION_OPEN_POPULATION:0 "Población"
 SETTING_INPUT_ACTION_OPEN_JOURNAL:0 "Diario"
 SETTING_INPUT_ACTION_OPEN_DECISIONS:0 "Decisiones"
 SETTING_INPUT_ACTION_MAP_LIST:0 "Libro de cuentas"
 SETTING_INPUT_ACTION_BACK:0 "Atrás"
 SETTING_INPUT_ACTION_OPEN_OUTLINER:0 "Esquematizador"
 SETTING_INPUT_ACTION_TAB_1:0 "Pestaña 1"
 SETTING_INPUT_ACTION_TAB_2:0 "Pestaña 2"
 SETTING_INPUT_ACTION_TAB_3:0 "Pestaña 3"
 SETTING_INPUT_ACTION_TAB_4:0 "Pestaña 4"
 SETTING_INPUT_ACTION_TAB_5:0 "Pestaña 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS:0 "Lente de producción"
 SETTING_INPUT_ACTION_POLITICAL_LENS:0 "Lente política"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS:0 "Lente diplomática"
 SETTING_INPUT_ACTION_MILITARY_LENS:0 "Lente militar"
 SETTING_INPUT_ACTION_TRADE_LENS:0 "Lente de comercio"
 SETTING_INPUT_ACTION_CONFIRM:0 "Confirmar"
 SETTING_INPUT_ACTION_CURRENT_SITUATION:0 "Situación actual"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE:0 "Cola de construcción"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE:0 "Pausar/reanudar cola de construcción"
 SETTING_INPUT_ACTION_GO_TO_DETAILS:0 "Ir a Detalles"
 SETTING_INPUT_ACTION_SCROLL_UP:0 "Desplazarse hacia arriba"
 SETTING_INPUT_ACTION_SCROLL_DOWN:0 "Desplazarse hacia abajo"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG:0 "(Depurar) gui.debug"
