l_spanish:
  # DELETE:
    # pm_disabled_gin
    # pm_disabled_elastics
    # pm_masticators
    # pm_rubber_bands
    # pm_luxury_clothes

  # Agriculture Buildings
 pm_primary:0 "Principal"
 pmg_secondary_building_rye_farm:0 "Secundario"
 pmg_secondary_building_wheat_farm:0 "Secundario"
 pmg_secondary_building_rice_farm:0 "Secundario"
 pmg_secondary_building_maize_farm:0 "Secundario"
 pmg_secondary_building_millet_farm:0 "Secundario"
 pm_no_secondary:0 "Mantener monocultivo"
 pm_potatoes:0 "Patatas"
 pm_vineyards:0 "Viñedos"
 pm_vineyards_building_maize_farm:0 "Viñedos"
 pm_apple_orchards:0 "Manzanares"
 pm_citrus_orchards:0 "Naranjales"
 pm_fig_orchards:0 "Higuerales"
 pm_mulberry_groves:0 "Morerales"

 pmg_automation:0 "Automatización"
 pmg_automation_building_food_industry:0 "Automatización"
 pmg_automation_building_textile_mills:0 "Automatización"
 pmg_automation_building_furniture_manufacturies:0 "Automatización"
 pmg_automation_building_tooling_workshops:0 "Automatización"
 pmg_automation_building_paper_mills:0 "Automatización"
 pmg_automation_building_steel_mills:0 "Automatización"
 pmg_automation_building_motor_industry:0 "Automatización"
 pm_civilian_priority:0 "Prioridad civil"
 pm_military_priority:0 "Prioridad militar"

  # Textile Mills
 pm_craftsman_sewing:0 "Costura artesanal"
 pm_sewing_machines:0 "Máquinas de coser"
 pm_electric_sewing_machines:0 "Máquinas de coser eléctricas"
 pm_traditional_looms:0 "Telares tradicionales"
 pm_mechanized_looms:0 "Telares mecanizados"
 pm_automatic_power_looms:0 "Telares eléctricos automáticos"

  # Glassworks
 pm_leaded_glass:0 "Vidrio emplomado"
 pm_manual_glassblowing:0 "Soplado de vidrio manual"

  # Chemical Plants
 pm_leblanc_process:0 "Proceso Leblanc"
 pm_no_explosives_production:0 "Priorizar producción de fertilizante"
 pm_ammonia-soda_process:0 "Proceso Solvay"
 pm_vacuum_evaporation:0 "Evaporación al vacío"
 pm_brine_electrolysis:0 "Electrólisis de salmuera"
 pmg_fertilizer_production:0 "Producción de fertilizantes"
 pm_no_artificial_fertilizers:0 "Sin fertilizantes artificiales"
 pm_artificial_fertilizers:0 "Fertilizantes artificiales"
 pm_improved_fertilizer:0 "Fertilizantes mejorados"
 pm_nitrogen_fixation:0 "Proceso de fijación de nitrógeno"
 pm_dyes_production:0 "Producción de tintes"
 pm_no_synthetic_dyes:0 "Sin tintes sintéticos"
 pmg_synthetic_dyes:0 "Tintes sintéticos"
 pm_silk_production:0 "Producción de seda"
 pm_no_artificial_fibers:0 "Priorizar producción de tintes"
 pm_rayon:0 "Rayón"

  # Foundries
 pm_steamworks:0 "Talleres con vapor"
 pm_no_artillery_production:0 "Priorizar producción de armas pequeñas"
 pm_artillery_production:0 "Producción de artillería"

  # Motor Industries
 pmg_automobile_production:0 "Producción de automóviles"
 pm_automobile_production:0 "Producción de automóviles"
